FROM node:20-alpine


RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app


COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


COPY ./packages ./packages
COPY ./apps/backend ./apps/backend


RUN pnpm install

RUN pnpm run db:generate

EXPOSE 8080

CMD ["pnpm", "run", "start:backend"]
